apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
    - port: "9113"
      interval: 10s