events {
    worker_connections 1024;
}

http {
    server {
        listen 8000;

        # Директория, куда будет смотреть nginx
        root /homework;

        # Файл index
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
    }
}
