apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
# nonResourceURLs невозможно установить для namespaced role
kind: ClusterRole 
metadata:
  name: metrics-reader
  namespace: homework
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-access
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: homework
roleRef:
  kind: Role
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
