apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 8000;

            root /homework;
            index index.html;

            location / {
                try_files $uri $uri/ =404;
            }

            error_page 404 /404.html;
        }
    }
