apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen 8000;
          server_name localhost;

          location / {
              root /homework;
              index index.html;
          }
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-intro
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          # Команда для удаления файла перед остановкой контейнера
          command: ["/bin/sh", "-c", "rm /homework/index.html"]
    volumeMounts:
    - name: workdir
      mountPath: /homework  # Монтируем volume в /homework
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf  # Монтируем кастомный конфиг
      subPath: nginx.conf  # Говорим, что это файл nginx.conf
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
  - name: nginx-config
    configMap:
      name: nginx-config-map  # Добавляем ConfigMap с конфигурацией Nginx
